---
openapi: 3.0.3
servers:
  - url: "http://localhost:8080/v1"
    description: Local machine
info:
  description: |-
    This service accepts mobility disruption information from mobility providers and makes them available for mobility apps
  version: 1.0.0
  title: Mobility Disruption Helper
paths:
  /disruptions:
    get:
      description: Gets the list of current disruptions
      operationId: getDisruptions
      parameters:
        - name: areaFrom
          required: true
          in: query
          schema:
            $ref: "#/components/schemas/Coordinate"
        - name: areaTo
          required: true
          in: query
          schema:
            $ref: "#/components/schemas/Coordinate"
      responses:
        "200":
          description: Returns the current disruptions in the given area
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Disruption"
                  
    post:
      description: Posts a new mobility disruption
      operationId: newDisruption
      requestBody:
        description: information about the new disruption
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewDisruption"
      responses:
        "200":
          description: Disruption was successfully accepted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Disruption"

components:
  schemas:
    Coordinate:
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number
        description:
          type: string

    NewDisruption:
      type: object
      properties:
        location:
          $ref: "#/components/schemas/Coordinate"

    Disruption:
      type: object
      allOf:
        - properties:
            id:
              type: string
              format: uuid
              description: Unique Id of disruption
        - $ref: "#/components/schemas/NewDisruption"
