---
version: '3.0'
services:
  service:
    build: ./backend/service
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres-disruptions:5432/disruptions
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=pwd
    ports:
      - 8080:8080

  postgres-disruptions:
    environment:
      - POSTGRES_PASSWORD=pwd
    image: bitnami/postgresql:11.11.0
    volumes:
      - ./disruptions-database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_disruptions:/var/lib/postgresql/data
    ports:
      - 5432:5432

#  frontend:

#  nats-server:
#    image: default-docker-3rdparty.bahnhub.tech.rz.db.de/nats:latest
#    ports:
#      - 4222:4222

volumes:
  postgres_data_disruptions:
    driver: local
  maven-cache:
    driver: local
